---
title: "Analyse données métabolome pour UC"
author: "Céline Lévy-Leduc"
date: ''
output:
  pdf_document: default
---

```{r}
install.packages("glmnet")
install.packages("reshape")
install.packages("MultiVarSel_1.0.tar.gz", repos = NULL, type = "source")
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())

#### Il faut d'abord installer MultiVarSel.tar.gz
#install.packages('MultiVarSel_1.0.tar.gz',repos=NULL)
#### Il faut au préalable installer glmnet et ggplot2

library(MultiVarSel)
#library(BlockCov)
library(reshape)   ### pour utiliser la fonction melt pour les boxplots
```

# Lecture des données

```{r}
table1=read.table("metabolome_Ath.csv", sep=";", header=T, dec=",")  
table1[1:3,1:10]

dim(table1)

table1[,1]

table=table1[,-1]

table[1:3,1:5]

#### Creation d'une variable qualitative supplementaire pour enlever les noms des replicats
temperature<-rep(c("FROID", "STD", "CHAUD"), each=3)
table2<-data.frame(temperature,table) # nouveau tableau
table2[1:3,1:10]

which(colMeans(table2[,2:dim(table2)[2]])==0)

which(apply(table2[,2:dim(table2)[2]],2,sd)==0)

which(is.na(table2))

```


# Matrices Y et X

```{r}
Y  <- as.matrix(table2[, -1])

X <- model.matrix(lm(Y ~ temperature + 0,data=table2))
p <- ncol(X)
n=nrow(X)
print(n)
q=dim(Y)[2]
print(q)

## Scaling the Y matrix (to force the empirical mean of each column
## to be 0 and the variance of each column to be 1)
Y=scale(Y)
```



```{r}
## Definition of the residuals
residus=lm(as.matrix(Y)~X-1)$residuals

## Whitening test without using any whitening method
pvalue=whitening_test(residus)
print(pvalue)

## Testing the two dependence structures (parametric : AR1 and Nonparametric) : Toeplitz case
whitening_choice(residus, typeDeps = c("AR1","nonparam"), pAR = 1, qMA = 0)

## => We will use the nonparametric modeling.

square_root_inv_hat_Sigma=whitening(residus,"nonparam",pAR=1,qMA=0)
```

```{r,echo=FALSE}
#### Modélisation par une matrice de covariance par blocs
# res_block=Sigma_estimation(residus, k = NULL, kmax = min(100, (q - 1)), nb_nn0 = NULL, seq.nb = NULL, step = 10, prop.max = 0.7, 
# big = FALSE,reorder = TRUE,inv_12 = TRUE)
# 
# image(Matrix(res_block$Sigma_est[res_block$order,res_block$order]))

```

```{r,echo=FALSE}
########################################
##### Choix du blanchiment #############
########################################

# cor_residus=cor(residus)
# mat_residus=cor_residus[upper.tri(cor_residus)]
# cor_res_blanch1=cor(residus%*%as.matrix(square_root_inv_hat_Sigma))
# mat_res_blanch1=cor_res_blanch1[upper.tri(cor_res_blanch1)]
# cor_res_blanch2=cor(residus%*%as.matrix(res_block$S_inv_12))
# mat_res_blanch2=cor_res_blanch2[upper.tri(cor_res_blanch2)]
# 
# res_blanch_data=data.frame(sans_blanch=mat_residus,
# blanch_toeplitz=mat_res_blanch1,blanch_bloc=mat_res_blanch2)
# 
# bx=ggplot(melt(res_blanch_data),aes(x=variable,y=value))+theme_bw()+
#   xlab('Methodes blanchiment')
# #bx+stat_summary(fun.data='mean_se')
# bx+geom_boxplot()+geom_hline(yintercept=0,color='red')

### Autre façon de faire un boxplot
#boxplot(res_blanch_data)
#abline(h=0,col='red')

```


```{r}
#### Sélection de variables

require(doMC) #### ne fonctionne pas sous windows
registerDoMC(cores=2)
#Freqs=variable_selection(Y,X,square_root_inv_hat_Sigma,nb_repli=5000,parallel=TRUE,nb.cores=2)
# save(Freqs, file='Freqs_metabolome_Ath_TOEPLITZ_nbreplis_5000.Rdata')

load('Freqs_metabolome_Ath_TOEPLITZ_nbreplis_5000.Rdata')

#Freqs=variable_selection(Y,X,res_block$S_inv_12,nb_repli=5000,parallel=TRUE,nb.cores=4)
#save(Freqs, file='Freqs_metabolome_Ath_BLOC_nbreplis_5000.Rdata')

#load('Freqs_metabolome_Ath_BLOC_nbreplis_5000.Rdata')

colnames(Freqs)<-c('Names_of_Y','Names_of_X','frequency')

plot(sort(Freqs$frequency,decreasing = T),type='s')

sort(Freqs$frequency,decreasing = T)[1:50]

```


```{r}
seuil=0.93

Freqs$Names_of_X=gsub(pattern='temperature',replacement='',Freqs$Names_of_X)

indices=which(Freqs$frequency>=seuil)

Yvec=as.numeric(Y%*%square_root_inv_hat_Sigma)
Xvec=kronecker(t(square_root_inv_hat_Sigma),X)
Xvec_sel=Xvec[,indices]
B_sel_hat=solve(t(Xvec_sel)%*%Xvec_sel,t(Xvec_sel)%*%Yvec)
Freqs$estim=rep(0,p*q)
Freqs$estim[indices]=as.vector(B_sel_hat)

library(ggplot2)
gr<-ggplot(data=Freqs[Freqs$frequency>=seuil,],
           aes(x=Names_of_Y,y=Names_of_X,color=estim))+
  scale_color_gradient2(low="steelblue",mid = "white", high ="red")+
  geom_point(size=2)+theme_bw()+
  ylab('Température')+
  xlab('Métabolites')+theme(axis.text.x = element_text(angle=90))
gr

```


```{r,fig.width=18,fig.height=20}

#### Boxplots

table_red=as.data.frame(Y[,colnames(Y)%in%unique(Freqs[indices,]$Names_of_Y)])
table_red$temperature=table2[,1]

bp <- ggplot(melt(table_red), aes(x=temperature, y=value,fill=temperature)) + 
  geom_boxplot()+theme_bw()+theme(axis.text.y =element_text(size=20),axis.text.x =element_text(size=15),axis.title =element_text(size=20),legend.title=element_text(size=20), 
    legend.text=element_text(size=19))
bp+facet_wrap(~variable,ncol=3)+ylab("Réponse")+theme(strip.text = element_text(face="bold", size=20))


#### Sans la fonction melt
# matrice=table_red[,1:length(unique(Freqs[indices,]$Names_of_Y))]
# table_boxplot=data.frame(Reponse=c(t(unlist(t(matrice)))),
#    temperature=rep(table_red$temperature,length(unique(Freqs[indices,]$Names_of_Y))),
#    nom=rep(unique(Freqs[indices,]$Names_of_Y),each=length(table_red$temperature)))
# 
# bp <- ggplot(table_boxplot, aes(x=temperature, y=Reponse)) + 
#   geom_boxplot()+theme_bw()
# bp+facet_wrap(~nom,ncol=3)

### Autre façon de faire un boxplot
# boxplot(Y[,which(colnames(Y)=="Maleate")]~temperature,main="Metabolite Maleate")
```

```{r,fig.width=10,fig.height=10,echo=FALSE}
liste_metabolites_selected=unique(Freqs[indices,]$Names_of_Y)
#length(liste_metabolites_selected)

#residus_red=residus[,colnames(residus)%in%liste_metabolites_selected]

#hc=hclust(dist(t(residus_red)),'ward')

# hc=hclust(dist(1 - abs(cor(residus_red))))
# plot(hc)
# rect.hclust(hc,k=5)
```

